Update build-openwrt.yml

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -66,96 +66,97 @@ jobs:
            df -h
 
     - name: Initialize environment
-	  run: |
-		  # 清理旧的源列表和 dotnet, android 等目录
-		  sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
+      run: |
+          # 清理旧的源列表和 dotnet, android 等目录
+          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
 
-		  # 更新APT源列表
-		  sudo apt-get -qq update || { echo "APT update failed"; exit 1; }
+          # 更新APT源列表
+          sudo apt-get -qq update || { echo "APT update failed"; exit 1; }
 
-		  # 升级已安装的软件包
-		  sudo apt-get -qq full-upgrade || { echo "APT upgrade failed"; exit 1; }
+          # 升级已安装的软件包
+          sudo apt-get -qq full-upgrade || { echo "APT upgrade failed"; exit 1; }
 
-		  # 安装依赖的软件包
-		  sudo apt-get -qq install \
-			ack \
-			antlr3 \
-			asciidoc \
-			autoconf \
-			automake \
-			autopoint \
-			binutils \
-			bison \
-			build-essential \
-			bzip2 \
-			ccache \
-			cmake \
-			cpio \
-			curl \
-			device-tree-compiler \
-			fastjar \
-			flex \
-			gawk \
-			gettext \
-			gcc-multilib \
-			g++-multilib \
-			git \
-			gperf \
-			haveged \
-			help2man \
-			intltool \
-			libc6-dev-i386 \
-			libelf-dev \
-			libglib2.0-dev \
-			libgmp3-dev \
-			libltdl-dev \
-			libmpc-dev \
-			libmpfr-dev \
-			libncurses5-dev \
-			libncursesw5-dev \
-			libreadline-dev \
-			libssl-dev \
-			libtool \
-			lrzsz \
-			mkisofs \
-			msmtp \
-			nano \
-			ninja-build \
-			p7zip \
-			p7zip-full \
-			patch \
-			pkgconf \
-			python3 \
-			python3-pyelftools \
-			libpython3-dev \
-			qemu-utils \
-			rsync \
-			scons \
-			squashfs-tools \
-			subversion \
-			swig \
-			texinfo \
-			uglifyjs \
-			upx-ucl \
-			unzip \
-			vim \
-			wget \
-			xmlto \
-			xxd \
-			zlib1g-dev || { echo "APT install failed"; exit 1; }
+          # 安装依赖的软件包
+          sudo apt-get -qq install \
+            ack \
+            antlr3 \
+            asciidoc \
+            autoconf \
+            automake \
+            autopoint \
+            binutils \
+            bison \
+            build-essential \
+            bzip2 \
+            ccache \
+            cmake \
+            cpio \
+            curl \
+            device-tree-compiler \
+            fastjar \
+            flex \
+            gawk \
+            gettext \
+            gcc-multilib \
+            g++-multilib \
+            git \
+            gperf \
+            haveged \
+            help2man \
+            intltool \
+            libc6-dev-i386 \
+            libelf-dev \
+            libglib2.0-dev \
+            libgmp3-dev \
+            libltdl-dev \
+            libmpc-dev \
+            libmpfr-dev \
+            libncurses5-dev \
+            libncursesw5-dev \
+            libreadline-dev \
+            libssl-dev \
+            libtool \
+            lrzsz \
+            mkisofs \
+            msmtp \
+            nano \
+            ninja-build \
+            p7zip \
+            p7zip-full \
+            patch \
+            pkgconf \
+            python3 \
+            python3-pyelftools \
+            libpython3-dev \
+            qemu-utils \
+            rsync \
+            scons \
+            squashfs-tools \
+            subversion \
+            swig \
+            texinfo \
+            uglifyjs \
+            upx-ucl \
+            unzip \
+            vim \
+            wget \
+            xmlto \
+            xxd \
+            zlib1g-dev || { echo "APT install failed"; exit 1; }
 
-		  # 移除不再需要的包
-		  sudo apt-get -qq autoremove --purge || { echo "APT autoremove failed"; exit 1; }
+          # 移除不再需要的包
+          sudo apt-get -qq autoremove --purge || { echo "APT autoremove failed"; exit 1; }
 
-		  # 清理APT缓存
-		  sudo apt-get -qq clean || { echo "APT clean failed"; exit 1; }
+          # 清理APT缓存
+          sudo apt-get -qq clean || { echo "APT clean failed"; exit 1; }
 
-		  # 设置时区
-		  sudo timedatectl set-timezone "$TZ"
+          # 设置时区
+          sudo timedatectl set-timezone "$TZ"
 
-		  # 创建工作目录
-		  sudo mkdir -p /workdir
-		  sudo chown $USER:$GROUPS /workdir
+          # 创建工作目录
+          sudo mkdir -p /workdir
+          sudo chown $USER:$GROUPS /workdir
+
 
 
         
